/*
 *
 * Atendee constants
 *
 */

export const OPEN_NEW_ATTENDEE_DIALOG = 'app/Atendee/OPEN_NEW_ATTENDEE_DIALOG';
export const CLOSE_NEW_ATTENDEE_DIALOG =
  'app/Atendee/CLOSE_NEW_ATTENDEE_DIALOG';
export const OPEN_EDIT_ATTENDEE_DIALOG =
  'app/Atendee/OPEN_EDIT_ATTENDEE_DIALOG';
export const CLOSE_EDIT_ATTENDEE_DIALOG =
  'app/Atendee/CLOSE_EDIT_ATTENDEE_DIALOG';

export const GET_ALL_ATTENDEES = 'app/Atendee/GET_ALL_ATTENDEES';
export const GET_ALL_ATTENDEES_SUCCESS =
  'app/Atendee/GET_ALL_ATTENDEES_SUCCESS';
export const GET_ALL_ATTENDEES_ERROR = 'app/Atendee/GET_ALL_ATTENDEES_ERROR';

export const SAVE_NEW_ATTENDEE = 'app/Atendee/SAVE_NEW_ATTENDEE';
export const SAVE_NEW_ATTENDEE_SUCCESS =
  'app/Atendee/SAVE_NEW_ATTENDEE_SUCCESS';
export const SAVE_NEW_ATTENDEE_ERROR = 'app/Atendee/SAVE_NEW_ATTENDEE_ERROR';

export const UPDATE_ATTENDEE = 'app/Atendee/UPDATE_ATTENDEE';
export const UPDATE_ATTENDEE_SUCCESS = 'app/Atendee/UPDATE_ATTENDEE_SUCCESS';
export const UPDATE_ATTENDEE_ERROR = 'app/Atendee/UPDATE_ATTENDEE_ERROR';

export const DELETE_ATTENDEE = 'app/Atendee/DELETE_ATTENDEE';
export const DELETE_ATTENDEE_SUCCESS = 'app/Atendee/DELETE_ATTENDEE_SUCCESS';
export const DELETE_ATTENDEE_ERROR = 'app/Atendee/DELETE_ATTENDEE_ERROR';
